# Generated by Django 4.0.3 on 2022-03-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('NumBooks', models.IntegerField()),
                ('DateDied', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookID', models.IntegerField()),
                ('ReleaseYear', models.IntegerField()),
                ('PageCount', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('RentPrice', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('SalePrice', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Damage', models.IntegerField()),
                ('LocationID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('StreetNum', models.IntegerField()),
                ('PostalCode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('LoginID', models.IntegerField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Detail',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('PurchaseAmt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rentail_Detail',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('RentAmt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Genres',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('BookGenre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('CardNo', models.IntegerField(primary_key=True, serialize=False)),
                ('CVV', models.IntegerField()),
                ('BillingAddress', models.CharField(max_length=50)),
                ('NameOnCard', models.CharField(max_length=50)),
                ('LoginID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('CardNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment')),
                ('LoginID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('Insurance_Prov_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('PolicyNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('CoverageDuration', models.IntegerField()),
                ('Details', models.CharField(max_length=100)),
                ('InsuranceProviderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Author_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Login_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('LoginID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.login')),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('AdminFlag', models.BooleanField(default=False)),
                ('CardNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Rating', models.IntegerField()),
                ('Comment', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Publishes',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Publisher_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_to_order',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Order_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.order')),
                ('Policy_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceplan')),
            ],
        ),
    ]
