# Generated by Django 4.0.2 on 2022-04-09 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('NumBooks', models.IntegerField()),
                ('FName', models.CharField(default='', max_length=50)),
                ('LName', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('ReleaseYear', models.IntegerField()),
                ('PageCount', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('RentPrice', models.IntegerField(null=True)),
                ('Title', models.CharField(max_length=50)),
                ('SalePrice', models.IntegerField(null=True)),
                ('Rating', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Damage', models.CharField(max_length=50)),
                ('LocationID', models.IntegerField()),
                ('Image', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('PolicyNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('CoverageDuration', models.IntegerField()),
                ('Details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('StreetNum', models.IntegerField()),
                ('PostalCode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('User_Email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('CardNo', models.IntegerField(primary_key=True, serialize=False)),
                ('CVV', models.IntegerField()),
                ('BillingAddress', models.CharField(max_length=50)),
                ('NameOnCard', models.CharField(max_length=50)),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Detail',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('StartDate', models.DateField(default=datetime.datetime(2022, 4, 8, 23, 35, 4, 230853))),
                ('EndDate', models.DateField()),
                ('RentAmt', models.IntegerField()),
                ('InsuranceProvider_Name', models.CharField(max_length=50)),
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book')),
                ('CardNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment')),
                ('Policy_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceplan')),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Detail',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('PurchaseAmt', models.IntegerField()),
                ('InsuranceProvider_Name', models.CharField(max_length=50)),
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book')),
                ('CardNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment')),
                ('Policy_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceplan')),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.location')),
            ],
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='InsuranceProvider_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceprovider'),
        ),
        migrations.AddField(
            model_name='book',
            name='Publisher_Name',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.publisher'),
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Author_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('User_Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.login')),
                ('Address', models.CharField(max_length=50)),
                ('DOB', models.DateField(null=True)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('AdminFlag', models.BooleanField(default=False)),
                ('CardNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BookMarketplaceApp.book')),
                ('Rating', models.IntegerField()),
                ('Comment', models.CharField(max_length=100)),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together={('PolicyNo', 'InsuranceProvider_Name')},
        ),
        migrations.CreateModel(
            name='Book_Genres',
            fields=[
                ('Genre_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BookGenre', models.CharField(max_length=20)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book')),
            ],
            options={
                'unique_together': {('Book_ID', 'BookGenre')},
            },
        ),
    ]
