# Generated by Django 4.0.2 on 2022-04-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0002_author_fname_author_lname_book_publisher_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='DateDied',
        ),
    ]
