# Generated by Django 4.0.3 on 2022-04-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CardNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.payment'),
        ),
    ]
