# Generated by Django 4.0.2 on 2022-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0003_remove_author_datedied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='AuthorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
