# Generated by Django 4.0.2 on 2022-04-09 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0004_rename_book_id_purchase_detail_bookid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental_detail',
            old_name='Book_ID',
            new_name='BookID',
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 38, 45, 119428)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 38, 45, 119428)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 38, 45, 119428)),
        ),
    ]
