# Generated by Django 4.0.2 on 2022-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0004_alter_author_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
