# Generated by Django 4.0.2 on 2022-04-09 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0005_rename_book_id_rental_detail_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_detail',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book'),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 41, 45, 404136)),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='Policy_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceplan'),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book'),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 41, 45, 404136)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='Policy_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.insuranceplan'),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 8, 23, 41, 45, 404136)),
        ),
    ]
