# Generated by Django 4.0.3 on 2022-04-10 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0006_alter_purchase_detail_bookid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 29, 33, 103158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 29, 33, 101982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 29, 33, 102983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('BookID', 'User_Email')},
        ),
    ]
