# Generated by Django 4.0.3 on 2022-04-10 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0007_review_id_alter_purchase_detail_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='Review_ID',
            field=models.AutoField(default=99, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 45, 28, 993518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 45, 28, 992521, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 1, 45, 28, 992521, tzinfo=utc)),
        ),
    ]
