# Generated by Django 4.0.3 on 2022-04-10 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0008_remove_review_id_review_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writes',
            name='Writes_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 7, 54, 12, 203404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 7, 54, 12, 202404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 7, 54, 12, 202404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='writes',
            name='Book_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book'),
        ),
        migrations.AlterUniqueTogether(
            name='writes',
            unique_together={('Book_ID', 'Author_ID')},
        ),
    ]
