# Generated by Django 4.0.3 on 2022-04-10 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0009_writes_writes_id_alter_purchase_detail_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 8, 4, 13, 782796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 8, 4, 13, 782796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='StartDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 8, 4, 13, 782796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='writes',
            name='Author_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.author'),
        ),
        migrations.AlterField(
            model_name='writes',
            name='Book_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMarketplaceApp.book'),
        ),
    ]
