# Generated by Django 4.0.2 on 2022-04-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0012_alter_wants_book_id_alter_wants_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='LocationID',
        ),
    ]
