# Generated by Django 4.0.2 on 2022-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0013_remove_book_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='LocationID',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
