# Generated by Django 4.0.2 on 2022-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMarketplaceApp', '0017_alter_book_rentprice_alter_book_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='PurchaseAmt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rental_detail',
            name='RentAmt',
            field=models.FloatField(),
        ),
    ]
